### ISSUE TITLE
/product-projections suggest implementation

### ISSUE THREAD

**Issue by cneijenhuis** [sphereio/commercetools-ios-sdk#49]
Support the `/product-projections/suggest` endpoint. It should take the parameters `limit` and `staged` (as in the Query of `/product-projections`).

It should also accept all other query parameters as specified in [1]:
* searchKeywords.{language} (Required, multiple keywords possible)
* fuzzy (Optional)

[1] http://dev.commercetools.com/http-api-projects-products-suggestions.html

**Comment by nikola-mladenovic** [comment]
Do we need to support _Suggestions For Two Languages_? If yes, then our data type question whether to use dictionary or an array of tuples arises again.

What are your thoughts @cneijenhuis ?

**Comment by cneijenhuis** [comment]
I don't really see a use-case for it, to be honest. Let's stick to a single language for now 👍

**Comment by nikola-mladenovic** [comment]
Great, thanks!
