### ISSUE TITLE
/product-types implementation

### ISSUE THREAD

**Issue by cneijenhuis** [sphereio/commercetools-ios-sdk#51]
Support the `/product-types` endpoint. It should support ById, ByKey and Query.

http://dev.commercetools.com/http-api-projects-productTypes.html

**Comment by nikola-mladenovic** [comment]
Some of the actions we're going to support require `manage_products` scope. AFAIK mobile clients will never have that scope on their end. Does it make sense to limit our support for only those actions possible with the regular mobile client scope `view_products manage_my_profile manage_my_orders` ?

**Comment by cneijenhuis** [comment]
The same is true for other endpoints.

I was thinking that it is useful to have that functionality for testing (as one can setup the testdata). However, as it is now super-easy to setup a "custom" endpoint that can do it, let's not support actions outside of the regular client scope 👍 

Instead, I'll add a ticket to write a bit of documentation on how test data cen be setup with custom endpoints.
