### ISSUE TITLE
Support Anonymous Cart and Checkout

### ISSUE THREAD

**Issue by cneijenhuis** [sphereio/commercetools-ios-sdk#58]
The SDK should be able to retrieve an anonymous `access_token`. It is a new endpoint on `auth.*`, but follows the semantics of the `client_credentials` flow. The `/me/carts/` and `/me/orders/` endpoints can be used afterwards.

`POST https://{host}/oauth/{projectKey}/anonymous/token?grant_type=client_credentials&scope={scope}` returns an `access_token` and a `refresh_token`. They should be handled similar to the tokens from the password flow.

Per default, the API generates an id for the anonymous token that is used across carts and orders. Optionally, the param `anonymous_id` can be specified to set a custom id. The API validates that this id has not been used yet.

The regular /me sign up [1] will automatically move the carts and orders from the anonymous token to the newly created customer. The SDK needs to do nothing new, just use the anonymous token.

Signing in with an anonymous token is a two-step process (like sign in):
* On `api.*` the customer is signed in
* On `auth.*` a password flow token is requested

For the first step, `POST /me/login` is to be used. Fields:
* `email` - String
* `password` - String
* `activeCartSignInMode` - [AnonymousCartSignInMode](http://dev.commercetools.com/http-api-projects-customers.html#anonymouscartsigninmode) - Optional

Otherwise `/me/login` behaves like [2] (i.e. fails on wrong email/password).

[1] http://dev.commercetools.com/http-api-projects-me-profile.html#create-customer-sign-up
[2] http://dev.commercetools.com/http-api-projects-customers.html#authenticate-customer-sign-in

**Comment by cneijenhuis** [comment]
The draft of my documentation is live here: http://ctp-198-40cb3a3.s3-website.eu-central-1.amazonaws.com/

See release notes and the tutorial: http://ctp-198-40cb3a3.s3-website.eu-central-1.amazonaws.com/tutorial-anonymous-session.html

I would prefer it if you'd use these instead of the description and let me know if you find any bugs in the documentation 👍

**Comment by nikola-mladenovic** [comment]
Yes, will do that 👍

**Comment by nikola-mladenovic** [comment]
So far, our SDK authorization flow was quite simple:

* On app launch, assuming this is the first one, app will obtain token (for the `client_credentials` flow), `AuthManager` will have it's `state` set to `PlainToken`
* If / when the user performs login, `AuthManager` obtains access and refresh token and sets it's `state` set to `CustomerToken`

Now, with anonymous session in place, what should we do with the previously implemented `client_credentials` flow? @cneijenhuis  Should that be removed? If not, how should the authorization flow look like now?

**Comment by cneijenhuis** [comment]
It is a valid use case that some apps don't want to support anonymous checkout/carts. (They may want to force the customer to create an account, or they do only work with existing accounts.)

Therefore, getting an anonymous token should not be forced.

One way would be to have the app developer trigger getting the anonymous token himself. This would also allow him/her to choose an `anonymous_id` (e.g. to identify the customer in some analytics software).

Another way is to have a configuration, so the app dev can choose what happens on app launch (`PlainToken` or `AnonymousToken`). This wouldn't allow the dev to choose the `anonymous_id`.

We could also support both. WDYT?

**Comment by nikola-mladenovic** [comment]
If it wasn't for the ability to set `anonymous_id` by the client, I would definitely say let's add a bool property to the config plist file which would be used to either get a `PlainToken` or `AnonymousToken`.

In order to give the ability to our SDK users to specify their own `anonymous_id`, we need to be able to obtain it before any SDK activity. The best way to accomplish this would be to declare `AnonymousIdentityDelegate` protocol. We will have a required method for providing the `anonymous_id` our client wants, and another optional, which will notify them whether the operation was successful, and if not, give the auto - generated ID.

`AuthManager.sharedInstance.identityDelegate` will need to be set (preferably in `func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool`) before setting the SDK configuration.

@cneijenhuis WDYT?

**Comment by cneijenhuis** [comment]
I like the idea of a delegate. But a valid flow would also be to start with a `PlainToken` and request the `AnonymousToken` only if necessary (e.g. add product to cart).

There could be two ways to use anonymous tokens: 
* Define it in the config. SDK will get an anonymous token immediately (if a delegate is provided with `anonymous_id`, otherwise not), and also in other circumstances (e.g. after `AuthManager.logoutUser()` is called)
* Not define it in the config. The app has to manually trigger it with the `AuthManager`.

**Comment by cneijenhuis** [comment]
The SDK could also provide a default delegate that will provide the device id (aka `identifierForVendor`).

**Comment by nikola-mladenovic** [comment]
> Define it in the config. SDK will get an anonymous token immediately (if a delegate is provided with anonymous_id, otherwise not), and also in other circumstances (e.g. after AuthManager.logoutUser() is called)
_if a delegate is provided with anonymous_id, otherwise not_ - the presence of the delegate only affects whether we'll try with custom `anonymous_id` or the one generated from the server.

**Comment by cneijenhuis** [comment]
Exactly, that is what I was trying to say 😉
