### ISSUE TITLE
Remove tokens on app uninstall

### ISSUE THREAD

**Issue by nikola-mladenovic** [sphereio/commercetools-ios-sdk#59]
Currently, the SDK is persisting tokens into keychain, which continues to live after the app is deleted.

The side affect of that behavior is our case is that the user remains logged in, even after the app is deleted and installed again.

In order to keep using keychain, but prevent this undesirable side effect, we can take the advantage of the fact that `NSUserDefaults` are removed on app deletion, so we just store a flag to indicate whether this is a fresh install or not.

**Comment by cneijenhuis** [comment]
I think it's a feature, not a bug :) Maybe we can document how one would implement logging out on a fresh install, if SDK users desire this behaviour.

**Comment by nkuehn** [comment]
I would be happy if my facebook, amazon etc. apps would still be logged in after a reinstall or such.
